[package]
name = "tokio-take-seek"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pin-project-lite = "0.2"
tokio = { version = "1", features = ["io-util"] }

[dev-dependencies]
tempfile = "1"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
